Fix wrapped array with null parsing into StdDeser
FasterXML/jackson-databind pull request #4844
Opened 2024-12-09 13:10 UTC by glorrian

Motivation: We encountered a bug in Micronaut Framework, when json parsing was rewritten so that any value is wrapped in an array(micronaut-projects/micronaut-core#10070) for the convenience of parsing multi values with one key, then the behavior when parsing null values began to throw an error, because jackson does not handle VALUE_NULL cases separately when parsing from a wrapped array. this pr is needed to fix this. 

fix issue: micronaut-projects/micronaut-core#11420

2024-12-09 23:52 UTC, JooHyukKim commented on src/test/java/com/fasterxml/jackson/databind/struct/UnwrapSingleArrayMiscTest.java
> +    }
declarations should go top

2024-12-09 23:52 UTC, JooHyukKim commented on src/test/java/com/fasterxml/jackson/databind/struct/UnwrapSingleArrayMiscTest.java
> +        String json = "{\"value\": [null]}";
Formatting + Exception is sort of convention now

```suggestion
    public void testDeserializeArrayWithNullElement()
        throws Exception
    {
        String json = "{\"value\": [null]}";
```

2024-12-09 23:52 UTC, JooHyukKim commented on src/test/java/com/fasterxml/jackson/databind/struct/UnwrapSingleArrayMiscTest.java
> +        assertNotNull(v);
Seperating lines would help making identifying expected behavior and execution easier

2024-12-09 23:52 UTC, JooHyukKim commented
Minor suggestions, looks clean tho

2024-12-10 01:19 UTC, cowtowncoder commented
Thank you @glorrian!  This is fix is correct: `deserialize()` is not expected to handle `null` values, caller should.

Aside from suggestions @JooHyukKim gave, one and only process thing we have is that we need to get CLA:

https://github.com/FasterXML/jackson/blob/master/contributor-agreement.pdf

(unless you have earlier sent one; CLA only needs to be sent once and is good for all contributions)

The easiest way is usually to print the doc, fill & sign, scan/photo, email to `cla` at fasterxml dot com.

Once I get it (or find existing one) I'm happy to merge this. I can also backport this in 2.18(.3) since it seems pretty safe to me.

Thank you again!

2024-12-10 01:52 UTC, JooHyukKim requested changes
Added comment wrt import ordering, thanks!

2024-12-10 01:52 UTC, JooHyukKim commented on src/test/java/com/fasterxml/jackson/databind/struct/UnwrapSingleArrayMiscTest.java
> +import com.fasterxml.jackson.core.JsonParser;
Oh also missed, wrt import ordering is [ jdk -> 3rd party -> jackson ] according to contributing guide.

```java
import java.io.IOException;
import java.util.Collections;
import java.util.EnumMap;
import java.util.Map;

import org.junit.jupiter.api.Test;

import com.fasterxml.jackson.core.JsonFactory;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.*;
import com.fasterxml.jackson.databind.exc.MismatchedInputException;
import com.fasterxml.jackson.databind.testutil.DatabindTestUtil;

import static org.junit.jupiter.api.Assertions.*;
```

2024-12-10 07:35 UTC, glorrian commented
hi, thank y'all for review, i sent my cla to clas at fasterxml dot com from glorrian55 at yandex dot ru, hope you'll receive it.

2024-12-10 07:41 UTC, glorrian commented
@JooHyukKim all your suggestions is completed

2024-12-10 09:21 UTC, JooHyukKim approved these changes

2024-12-10 09:21 UTC, JooHyukKim commented
LGMT! Thank u @glorrian

2024-12-10 10:13 UTC, yawkat commented
Thanks for tracking this down!

2024-12-11 10:27 UTC, glorrian commented
@cowtowncoder i try to send from different mail, check it pls
it gonna be mail from `sherbakov05.bkmail.ru@gmail.com`

2024-12-12 00:44 UTC, cowtowncoder commented
> @cowtowncoder i try to send from different mail to info and cla both, check it pls it gonna be mail from `sherbakov05.bkmail.ru@gmail.com`

@glorrian Got it now, thanks!

2024-12-12 00:56 UTC, merged

2024-12-12 01:48 UTC, cowtowncoder commented
Merged, thank you @glorrian for the report & fix!